DROP TABLE IF EXISTS CONFIGURATION;
  
CREATE TABLE CONFIGURATION (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  PROPERTY VARCHAR(64) NOT NULL,
  PROPERTY_VALUE VARCHAR(255) NOT NULL
);

CREATE TABLE OAUTH_CLIENT_DETAILS (
  CLIENT_ID VARCHAR(255) NOT NULL,
  MAP_TO_BACKEND_ID VARCHAR(255) NOT NULL
);

ALTER TABLE "CONFIGURATION"
ADD CONSTRAINT TEST_UNIQUE
UNIQUE ( PROPERTY );


