/* AssentSoftware (C)2023 */
package com.decathlon.data.manager;

import com.decathlon.data.domain.Persona;

public interface PersonService {

    Persona save(Persona entityToSave);

    Persona saveCodeNotAutoGenerated(Persona entityToSave);

    Persona getById(Long id);
}
