/* Decathlon (C)2021 */
package com.decathlon.rest.crud.entities;
// Generated 7 dic. 2021 10:22:07 by Hibernate Tools 3.2.2.GA and Assent Architecture

import com.decathlon.core.domain.types.Auditable;
import com.decathlon.core.domain.types.Identifiable;
import com.decathlon.core.domain.types.Versionable;

import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;

import java.io.Serializable;
import java.time.LocalDateTime;

/** CodigoPostal generated by hbm2java */
public class CodigoPostal implements Versionable, Identifiable, Auditable, Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;

    private long version;

    private Provincia provincia;

    private Poblacion poblacion;

    private String codigoPostal;
    @CreatedBy private String usuarioCreacion;
    @CreatedDate private LocalDateTime fechaCreacion;
    @LastModifiedBy private String usuarioModificacion;
    @LastModifiedDate private LocalDateTime fechaModificacion;

    public CodigoPostal() {
        // default constructor
    }

    public CodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }

    public CodigoPostal(
            Provincia provincia,
            Poblacion poblacion,
            String codigoPostal,
            String usuarioCreacion,
            LocalDateTime fechaCreacion,
            String usuarioModificacion,
            LocalDateTime fechaModificacion) {
        this.provincia = provincia;
        this.poblacion = poblacion;
        this.codigoPostal = codigoPostal;
        this.usuarioCreacion = usuarioCreacion;
        this.fechaCreacion = fechaCreacion;
        this.usuarioModificacion = usuarioModificacion;
        this.fechaModificacion = fechaModificacion;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getVersion() {
        return this.version;
    }

    public void setVersion(long version) {
        this.version = version;
    }

    public Provincia getProvincia() {
        return this.provincia;
    }

    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }

    public Poblacion getPoblacion() {
        return this.poblacion;
    }

    public void setPoblacion(Poblacion poblacion) {
        this.poblacion = poblacion;
    }

    public String getCodigoPostal() {
        return this.codigoPostal;
    }

    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }

    @Override
    public String getCreatedBy() {
        return usuarioCreacion;
    }

    @Override
    public void setCreatedBy(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }

    @Override
    public LocalDateTime getCreatedAt() {
        return fechaCreacion;
    }

    @Override
    public void setCreatedAt(LocalDateTime fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Override
    public String getLastModifiedBy() {
        return usuarioModificacion;
    }

    @Override
    public void setLastModifiedBy(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }

    @Override
    public LocalDateTime getLastModifiedDate() {
        return fechaModificacion;
    }

    @Override
    public void setLastModifiedDate(LocalDateTime fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    /**
     * toString
     *
     * @return String
     */
    @Override
    public String toString() {
        StringBuilder buffer = new StringBuilder();

        buffer.append(getClass().getName())
                .append("@")
                .append(Integer.toHexString(hashCode()))
                .append(" [");
        buffer.append("id").append("='").append(getId()).append("' ");
        buffer.append("version").append("='").append(getVersion()).append("' ");
        buffer.append("provincia").append("='").append(getProvincia()).append("' ");
        buffer.append("poblacion").append("='").append(getPoblacion()).append("' ");
        buffer.append("codigoPostal").append("='").append(getCodigoPostal()).append("' ");
        buffer.append("usuarioCreacion").append("='").append(getCreatedBy()).append("' ");
        buffer.append("fechaCreacion").append("='").append(getCreatedAt()).append("' ");
        buffer.append("usuarioModificacion").append("='").append(getLastModifiedBy()).append("' ");
        buffer.append("fechaModificacion").append("='").append(getLastModifiedDate()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;

        if (other == null) return false;

        if (!(other instanceof CodigoPostal)) return false;

        CodigoPostal castOther = (CodigoPostal) other;

        return ((this.getId() == castOther.getId())
                        || (this.getId() != null
                                && castOther.getId() != null
                                && this.getId().equals(castOther.getId())))
                && (this.getVersion() == castOther.getVersion());
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
        result = 37 * result + (int) this.getVersion();

        return result;
    }
}
