/* Decathlon (C)2021 */
package com.decathlon.rest.crud.entities;
// Generated 7 dic. 2021 10:22:07 by Hibernate Tools 3.2.2.GA and Assent Architecture

import com.decathlon.core.domain.types.Auditable;
import com.decathlon.core.domain.types.Identifiable;
import com.decathlon.core.domain.types.Versionable;

import java.time.LocalDate;
import java.time.LocalDateTime;

/** Persona generated by hbm2java */
public class Persona implements Versionable, Identifiable, Auditable, java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;

    private long version;

    private Sexo sexo;

    private CodigoPostal codigoPostal;

    private String codigoPersona;

    private String cedulaPersona;

    private String nombrePersona;

    private String apellidoPersona;

    private String rifPersona;

    private String numeroMsas;

    private LocalDate fechaNacimientoPersona;

    private LocalDate fechaDefuncionPersona;

    private LocalDate fechaVencimientoRif;

    private String telefonoMovilPersona;

    private String telefonoFijoPersona;

    private String EMailPersona;

    private String direccionPersona;

    private String nombreContactoUno;

    private String telefonoContactoUno;

    private String telefonoMovilContactoUno;

    private String emailContactoUno;

    private String parentescoContactoUno;

    private String nombreContactoDos;

    private String telefonoContactoDos;

    private String telefonoMovilContactoDos;

    private String emailContactoDos;

    private String parentescoContactoDos;

    private Float edad;

    private String url1;

    private String url1FileName;

    private Double url1FileSize;

    private String comentariosAdicionales;

    private String nombreDoctorReferencia;

    private String telefonoContactoDoctorReferencia;

    private String telefonoMovilDoctorReferencia;

    private String emailDoctorReferencia;

    private String lugarNacimientoOtro;

    private String direccionPersonaCalleAvenida;

    private String direccionPersonaEdificio;

    private String direccionPersonaConsultorio;
    private String usuarioCreacion;
    private LocalDateTime fechaCreacion;
    private String usuarioModificacion;
    private LocalDateTime fechaModificacion;

    public Persona() {
        // default constructor
    }

    public Persona(
            String codigoPersona,
            String cedulaPersona,
            String nombrePersona,
            String telefonoFijoPersona,
            String direccionPersona) {
        this.codigoPersona = codigoPersona;
        this.cedulaPersona = cedulaPersona;
        this.nombrePersona = nombrePersona;
        this.telefonoFijoPersona = telefonoFijoPersona;
        this.direccionPersona = direccionPersona;
    }

    public Persona(
            Sexo sexo,
            CodigoPostal codigoPostal,
            String codigoPersona,
            String cedulaPersona,
            String nombrePersona,
            String apellidoPersona,
            String rifPersona,
            String numeroMsas,
            LocalDate fechaNacimientoPersona,
            LocalDate fechaDefuncionPersona,
            LocalDate fechaVencimientoRif,
            String telefonoMovilPersona,
            String telefonoFijoPersona,
            String EMailPersona,
            String direccionPersona,
            String nombreContactoUno,
            String telefonoContactoUno,
            String telefonoMovilContactoUno,
            String emailContactoUno,
            String parentescoContactoUno,
            String nombreContactoDos,
            String telefonoContactoDos,
            String telefonoMovilContactoDos,
            String emailContactoDos,
            String parentescoContactoDos,
            Float edad,
            String url1,
            String url1FileName,
            Double url1FileSize,
            String comentariosAdicionales,
            String nombreDoctorReferencia,
            String telefonoContactoDoctorReferencia,
            String telefonoMovilDoctorReferencia,
            String emailDoctorReferencia,
            String lugarNacimientoOtro,
            String direccionPersonaCalleAvenida,
            String direccionPersonaEdificio,
            String direccionPersonaConsultorio,
            String usuarioCreacion,
            LocalDateTime fechaCreacion,
            String usuarioModificacion,
            LocalDateTime fechaModificacion) {
        this.sexo = sexo;
        this.codigoPostal = codigoPostal;
        this.codigoPersona = codigoPersona;
        this.cedulaPersona = cedulaPersona;
        this.nombrePersona = nombrePersona;
        this.apellidoPersona = apellidoPersona;
        this.rifPersona = rifPersona;
        this.numeroMsas = numeroMsas;
        this.fechaNacimientoPersona = fechaNacimientoPersona;
        this.fechaDefuncionPersona = fechaDefuncionPersona;
        this.fechaVencimientoRif = fechaVencimientoRif;
        this.telefonoMovilPersona = telefonoMovilPersona;
        this.telefonoFijoPersona = telefonoFijoPersona;
        this.EMailPersona = EMailPersona;
        this.direccionPersona = direccionPersona;
        this.nombreContactoUno = nombreContactoUno;
        this.telefonoContactoUno = telefonoContactoUno;
        this.telefonoMovilContactoUno = telefonoMovilContactoUno;
        this.emailContactoUno = emailContactoUno;
        this.parentescoContactoUno = parentescoContactoUno;
        this.nombreContactoDos = nombreContactoDos;
        this.telefonoContactoDos = telefonoContactoDos;
        this.telefonoMovilContactoDos = telefonoMovilContactoDos;
        this.emailContactoDos = emailContactoDos;
        this.parentescoContactoDos = parentescoContactoDos;
        this.edad = edad;
        this.url1 = url1;
        this.url1FileName = url1FileName;
        this.url1FileSize = url1FileSize;
        this.comentariosAdicionales = comentariosAdicionales;
        this.nombreDoctorReferencia = nombreDoctorReferencia;
        this.telefonoContactoDoctorReferencia = telefonoContactoDoctorReferencia;
        this.telefonoMovilDoctorReferencia = telefonoMovilDoctorReferencia;
        this.emailDoctorReferencia = emailDoctorReferencia;
        this.lugarNacimientoOtro = lugarNacimientoOtro;
        this.direccionPersonaCalleAvenida = direccionPersonaCalleAvenida;
        this.direccionPersonaEdificio = direccionPersonaEdificio;
        this.direccionPersonaConsultorio = direccionPersonaConsultorio;
        this.usuarioCreacion = usuarioCreacion;
        this.fechaCreacion = fechaCreacion;
        this.usuarioModificacion = usuarioModificacion;
        this.fechaModificacion = fechaModificacion;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getVersion() {
        return this.version;
    }

    public void setVersion(long version) {
        this.version = version;
    }

    public Sexo getSexo() {
        return this.sexo;
    }

    public void setSexo(Sexo sexo) {
        this.sexo = sexo;
    }

    public CodigoPostal getCodigoPostal() {
        return this.codigoPostal;
    }

    public void setCodigoPostal(CodigoPostal codigoPostal) {
        this.codigoPostal = codigoPostal;
    }

    public String getCodigoPersona() {
        return this.codigoPersona;
    }

    public void setCodigoPersona(String codigoPersona) {
        this.codigoPersona = codigoPersona;
    }

    public String getCedulaPersona() {
        return this.cedulaPersona;
    }

    public void setCedulaPersona(String cedulaPersona) {
        this.cedulaPersona = cedulaPersona;
    }

    public String getNombrePersona() {
        return this.nombrePersona;
    }

    public void setNombrePersona(String nombrePersona) {
        this.nombrePersona = nombrePersona;
    }

    public String getApellidoPersona() {
        return this.apellidoPersona;
    }

    public void setApellidoPersona(String apellidoPersona) {
        this.apellidoPersona = apellidoPersona;
    }

    public String getRifPersona() {
        return this.rifPersona;
    }

    public void setRifPersona(String rifPersona) {
        this.rifPersona = rifPersona;
    }

    public String getNumeroMsas() {
        return this.numeroMsas;
    }

    public void setNumeroMsas(String numeroMsas) {
        this.numeroMsas = numeroMsas;
    }

    public LocalDate getFechaNacimientoPersona() {
        return this.fechaNacimientoPersona;
    }

    public void setFechaNacimientoPersona(LocalDate fechaNacimientoPersona) {
        this.fechaNacimientoPersona = fechaNacimientoPersona;
    }

    public LocalDate getFechaDefuncionPersona() {
        return this.fechaDefuncionPersona;
    }

    public void setFechaDefuncionPersona(LocalDate fechaDefuncionPersona) {
        this.fechaDefuncionPersona = fechaDefuncionPersona;
    }

    public LocalDate getFechaVencimientoRif() {
        return this.fechaVencimientoRif;
    }

    public void setFechaVencimientoRif(LocalDate fechaVencimientoRif) {
        this.fechaVencimientoRif = fechaVencimientoRif;
    }

    public String getTelefonoMovilPersona() {
        return this.telefonoMovilPersona;
    }

    public void setTelefonoMovilPersona(String telefonoMovilPersona) {
        this.telefonoMovilPersona = telefonoMovilPersona;
    }

    public String getTelefonoFijoPersona() {
        return this.telefonoFijoPersona;
    }

    public void setTelefonoFijoPersona(String telefonoFijoPersona) {
        this.telefonoFijoPersona = telefonoFijoPersona;
    }

    public String getEMailPersona() {
        return this.EMailPersona;
    }

    public void setEMailPersona(String EMailPersona) {
        this.EMailPersona = EMailPersona;
    }

    public String getDireccionPersona() {
        return this.direccionPersona;
    }

    public void setDireccionPersona(String direccionPersona) {
        this.direccionPersona = direccionPersona;
    }

    public String getNombreContactoUno() {
        return this.nombreContactoUno;
    }

    public void setNombreContactoUno(String nombreContactoUno) {
        this.nombreContactoUno = nombreContactoUno;
    }

    public String getTelefonoContactoUno() {
        return this.telefonoContactoUno;
    }

    public void setTelefonoContactoUno(String telefonoContactoUno) {
        this.telefonoContactoUno = telefonoContactoUno;
    }

    public String getTelefonoMovilContactoUno() {
        return this.telefonoMovilContactoUno;
    }

    public void setTelefonoMovilContactoUno(String telefonoMovilContactoUno) {
        this.telefonoMovilContactoUno = telefonoMovilContactoUno;
    }

    public String getEmailContactoUno() {
        return this.emailContactoUno;
    }

    public void setEmailContactoUno(String emailContactoUno) {
        this.emailContactoUno = emailContactoUno;
    }

    public String getParentescoContactoUno() {
        return this.parentescoContactoUno;
    }

    public void setParentescoContactoUno(String parentescoContactoUno) {
        this.parentescoContactoUno = parentescoContactoUno;
    }

    public String getNombreContactoDos() {
        return this.nombreContactoDos;
    }

    public void setNombreContactoDos(String nombreContactoDos) {
        this.nombreContactoDos = nombreContactoDos;
    }

    public String getTelefonoContactoDos() {
        return this.telefonoContactoDos;
    }

    public void setTelefonoContactoDos(String telefonoContactoDos) {
        this.telefonoContactoDos = telefonoContactoDos;
    }

    public String getTelefonoMovilContactoDos() {
        return this.telefonoMovilContactoDos;
    }

    public void setTelefonoMovilContactoDos(String telefonoMovilContactoDos) {
        this.telefonoMovilContactoDos = telefonoMovilContactoDos;
    }

    public String getEmailContactoDos() {
        return this.emailContactoDos;
    }

    public void setEmailContactoDos(String emailContactoDos) {
        this.emailContactoDos = emailContactoDos;
    }

    public String getParentescoContactoDos() {
        return this.parentescoContactoDos;
    }

    public void setParentescoContactoDos(String parentescoContactoDos) {
        this.parentescoContactoDos = parentescoContactoDos;
    }

    public Float getEdad() {
        return this.edad;
    }

    public void setEdad(Float edad) {
        this.edad = edad;
    }

    public String getUrl1() {
        return this.url1;
    }

    public void setUrl1(String url1) {
        this.url1 = url1;
    }

    public String getUrl1FileName() {
        return this.url1FileName;
    }

    public void setUrl1FileName(String url1FileName) {
        this.url1FileName = url1FileName;
    }

    public Double getUrl1FileSize() {
        return this.url1FileSize;
    }

    public void setUrl1FileSize(Double url1FileSize) {
        this.url1FileSize = url1FileSize;
    }

    public String getComentariosAdicionales() {
        return this.comentariosAdicionales;
    }

    public void setComentariosAdicionales(String comentariosAdicionales) {
        this.comentariosAdicionales = comentariosAdicionales;
    }

    public String getNombreDoctorReferencia() {
        return this.nombreDoctorReferencia;
    }

    public void setNombreDoctorReferencia(String nombreDoctorReferencia) {
        this.nombreDoctorReferencia = nombreDoctorReferencia;
    }

    public String getTelefonoContactoDoctorReferencia() {
        return this.telefonoContactoDoctorReferencia;
    }

    public void setTelefonoContactoDoctorReferencia(String telefonoContactoDoctorReferencia) {
        this.telefonoContactoDoctorReferencia = telefonoContactoDoctorReferencia;
    }

    public String getTelefonoMovilDoctorReferencia() {
        return this.telefonoMovilDoctorReferencia;
    }

    public void setTelefonoMovilDoctorReferencia(String telefonoMovilDoctorReferencia) {
        this.telefonoMovilDoctorReferencia = telefonoMovilDoctorReferencia;
    }

    public String getEmailDoctorReferencia() {
        return this.emailDoctorReferencia;
    }

    public void setEmailDoctorReferencia(String emailDoctorReferencia) {
        this.emailDoctorReferencia = emailDoctorReferencia;
    }

    public String getLugarNacimientoOtro() {
        return this.lugarNacimientoOtro;
    }

    public void setLugarNacimientoOtro(String lugarNacimientoOtro) {
        this.lugarNacimientoOtro = lugarNacimientoOtro;
    }

    public String getDireccionPersonaCalleAvenida() {
        return this.direccionPersonaCalleAvenida;
    }

    public void setDireccionPersonaCalleAvenida(String direccionPersonaCalleAvenida) {
        this.direccionPersonaCalleAvenida = direccionPersonaCalleAvenida;
    }

    public String getDireccionPersonaEdificio() {
        return this.direccionPersonaEdificio;
    }

    public void setDireccionPersonaEdificio(String direccionPersonaEdificio) {
        this.direccionPersonaEdificio = direccionPersonaEdificio;
    }

    public String getDireccionPersonaConsultorio() {
        return this.direccionPersonaConsultorio;
    }

    public void setDireccionPersonaConsultorio(String direccionPersonaConsultorio) {
        this.direccionPersonaConsultorio = direccionPersonaConsultorio;
    }

    @Override
    public String getCreatedBy() {
        return usuarioCreacion;
    }

    @Override
    public void setCreatedBy(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }

    @Override
    public LocalDateTime getCreatedAt() {
        return fechaCreacion;
    }

    @Override
    public void setCreatedAt(LocalDateTime fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Override
    public String getLastModifiedBy() {
        return usuarioModificacion;
    }

    @Override
    public void setLastModifiedBy(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }

    @Override
    public LocalDateTime getLastModifiedDate() {
        return fechaModificacion;
    }

    @Override
    public void setLastModifiedDate(LocalDateTime fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    /**
     * toString
     *
     * @return String
     */
    @Override
    public String toString() {
        StringBuilder buffer = new StringBuilder();

        buffer.append(getClass().getName())
                .append("@")
                .append(Integer.toHexString(hashCode()))
                .append(" [");
        buffer.append("id").append("='").append(getId()).append("' ");
        buffer.append("version").append("='").append(getVersion()).append("' ");
        buffer.append("sexo").append("='").append(getSexo()).append("' ");
        buffer.append("codigoPostal").append("='").append(getCodigoPostal()).append("' ");
        buffer.append("codigoPersona").append("='").append(getCodigoPersona()).append("' ");
        buffer.append("cedulaPersona").append("='").append(getCedulaPersona()).append("' ");
        buffer.append("nombrePersona").append("='").append(getNombrePersona()).append("' ");
        buffer.append("apellidoPersona").append("='").append(getApellidoPersona()).append("' ");
        buffer.append("rifPersona").append("='").append(getRifPersona()).append("' ");
        buffer.append("numeroMsas").append("='").append(getNumeroMsas()).append("' ");
        buffer.append("fechaNacimientoPersona")
                .append("='")
                .append(getFechaNacimientoPersona())
                .append("' ");
        buffer.append("fechaDefuncionPersona")
                .append("='")
                .append(getFechaDefuncionPersona())
                .append("' ");
        buffer.append("fechaVencimientoRif")
                .append("='")
                .append(getFechaVencimientoRif())
                .append("' ");
        buffer.append("telefonoMovilPersona")
                .append("='")
                .append(getTelefonoMovilPersona())
                .append("' ");
        buffer.append("telefonoFijoPersona")
                .append("='")
                .append(getTelefonoFijoPersona())
                .append("' ");
        buffer.append("EMailPersona").append("='").append(getEMailPersona()).append("' ");
        buffer.append("direccionPersona").append("='").append(getDireccionPersona()).append("' ");
        buffer.append("nombreContactoUno").append("='").append(getNombreContactoUno()).append("' ");
        buffer.append("telefonoContactoUno")
                .append("='")
                .append(getTelefonoContactoUno())
                .append("' ");
        buffer.append("telefonoMovilContactoUno")
                .append("='")
                .append(getTelefonoMovilContactoUno())
                .append("' ");
        buffer.append("emailContactoUno").append("='").append(getEmailContactoUno()).append("' ");
        buffer.append("parentescoContactoUno")
                .append("='")
                .append(getParentescoContactoUno())
                .append("' ");
        buffer.append("nombreContactoDos").append("='").append(getNombreContactoDos()).append("' ");
        buffer.append("telefonoContactoDos")
                .append("='")
                .append(getTelefonoContactoDos())
                .append("' ");
        buffer.append("telefonoMovilContactoDos")
                .append("='")
                .append(getTelefonoMovilContactoDos())
                .append("' ");
        buffer.append("emailContactoDos").append("='").append(getEmailContactoDos()).append("' ");
        buffer.append("parentescoContactoDos")
                .append("='")
                .append(getParentescoContactoDos())
                .append("' ");
        buffer.append("edad").append("='").append(getEdad()).append("' ");
        buffer.append("url1").append("='").append(getUrl1()).append("' ");
        buffer.append("url1FileName").append("='").append(getUrl1FileName()).append("' ");
        buffer.append("url1FileSize").append("='").append(getUrl1FileSize()).append("' ");
        buffer.append("comentariosAdicionales")
                .append("='")
                .append(getComentariosAdicionales())
                .append("' ");
        buffer.append("nombreDoctorReferencia")
                .append("='")
                .append(getNombreDoctorReferencia())
                .append("' ");
        buffer.append("telefonoContactoDoctorReferencia")
                .append("='")
                .append(getTelefonoContactoDoctorReferencia())
                .append("' ");
        buffer.append("telefonoMovilDoctorReferencia")
                .append("='")
                .append(getTelefonoMovilDoctorReferencia())
                .append("' ");
        buffer.append("emailDoctorReferencia")
                .append("='")
                .append(getEmailDoctorReferencia())
                .append("' ");
        buffer.append("lugarNacimientoOtro")
                .append("='")
                .append(getLugarNacimientoOtro())
                .append("' ");
        buffer.append("direccionPersonaCalleAvenida")
                .append("='")
                .append(getDireccionPersonaCalleAvenida())
                .append("' ");
        buffer.append("direccionPersonaEdificio")
                .append("='")
                .append(getDireccionPersonaEdificio())
                .append("' ");
        buffer.append("direccionPersonaConsultorio")
                .append("='")
                .append(getDireccionPersonaConsultorio())
                .append("' ");
        buffer.append("usuarioCreacion").append("='").append(getCreatedBy()).append("' ");
        buffer.append("fechaCreacion").append("='").append(getCreatedAt()).append("' ");
        buffer.append("usuarioModificacion").append("='").append(getLastModifiedBy()).append("' ");
        buffer.append("fechaModificacion").append("='").append(getLastModifiedDate()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;

        if (other == null) return false;

        if (!(other instanceof Persona)) return false;

        Persona castOther = (Persona) other;

        return ((this.getId() == castOther.getId())
                        || (this.getId() != null
                                && castOther.getId() != null
                                && this.getId().equals(castOther.getId())))
                && (this.getVersion() == castOther.getVersion());
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
        result = 37 * result + (int) this.getVersion();

        return result;
    }
}
