/* Decathlon (C)2021 */
package com.decathlon.rest.crud.entities;
// Generated 7 dic. 2021 10:22:07 by Hibernate Tools 3.2.2.GA and Assent Architecture

import com.decathlon.core.domain.types.Auditable;
import com.decathlon.core.domain.types.Identifiable;
import com.decathlon.core.domain.types.Versionable;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

/** Provincia generated by hbm2java */
public class Provincia implements Versionable, Identifiable, Auditable, java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;

    private long version;

    private String codigoProvincia;

    private String nombreProvincia;
    private String usuarioCreacion;
    private LocalDateTime fechaCreacion;
    private String usuarioModificacion;
    private LocalDateTime fechaModificacion;

    private Set<CodigoPostal> codigoPostals = new HashSet<CodigoPostal>(0);

    public Provincia() {
        // default constructor
    }

    public Provincia(String codigoProvincia, String nombreProvincia) {
        this.codigoProvincia = codigoProvincia;
        this.nombreProvincia = nombreProvincia;
    }

    public Provincia(
            String codigoProvincia,
            String nombreProvincia,
            String usuarioCreacion,
            LocalDateTime fechaCreacion,
            String usuarioModificacion,
            LocalDateTime fechaModificacion,
            Set<CodigoPostal> codigoPostals) {
        this.codigoProvincia = codigoProvincia;
        this.nombreProvincia = nombreProvincia;
        this.usuarioCreacion = usuarioCreacion;
        this.fechaCreacion = fechaCreacion;
        this.usuarioModificacion = usuarioModificacion;
        this.fechaModificacion = fechaModificacion;
        this.codigoPostals = codigoPostals;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getVersion() {
        return this.version;
    }

    public void setVersion(long version) {
        this.version = version;
    }

    public String getCodigoProvincia() {
        return this.codigoProvincia;
    }

    public void setCodigoProvincia(String codigoProvincia) {
        this.codigoProvincia = codigoProvincia;
    }

    public String getNombreProvincia() {
        return this.nombreProvincia;
    }

    public void setNombreProvincia(String nombreProvincia) {
        this.nombreProvincia = nombreProvincia;
    }

    @Override
    public String getCreatedBy() {
        return usuarioCreacion;
    }

    @Override
    public void setCreatedBy(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }

    @Override
    public LocalDateTime getCreatedAt() {
        return fechaCreacion;
    }

    @Override
    public void setCreatedAt(LocalDateTime fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Override
    public String getLastModifiedBy() {
        return usuarioModificacion;
    }

    @Override
    public void setLastModifiedBy(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }

    @Override
    public LocalDateTime getLastModifiedDate() {
        return fechaModificacion;
    }

    @Override
    public void setLastModifiedDate(LocalDateTime fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    // @JsonIgnore
    public Set<CodigoPostal> getCodigoPostals() {
        return this.codigoPostals;
    }

    public void setCodigoPostals(Set<CodigoPostal> codigoPostals) {
        this.codigoPostals = codigoPostals;
    }

    /**
     * toString
     *
     * @return String
     */
    @Override
    public String toString() {
        StringBuilder buffer = new StringBuilder();

        buffer.append(getClass().getName())
                .append("@")
                .append(Integer.toHexString(hashCode()))
                .append(" [");
        buffer.append("id").append("='").append(getId()).append("' ");
        buffer.append("version").append("='").append(getVersion()).append("' ");
        buffer.append("codigoProvincia").append("='").append(getCodigoProvincia()).append("' ");
        buffer.append("nombreProvincia").append("='").append(getNombreProvincia()).append("' ");
        buffer.append("usuarioCreacion").append("='").append(getCreatedBy()).append("' ");
        buffer.append("fechaCreacion").append("='").append(getCreatedAt()).append("' ");
        buffer.append("usuarioModificacion").append("='").append(getLastModifiedBy()).append("' ");
        buffer.append("fechaModificacion").append("='").append(getLastModifiedDate()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;

        if (other == null) return false;

        if (!(other instanceof Provincia)) return false;

        Provincia castOther = (Provincia) other;

        return ((this.getId() == castOther.getId())
                        || (this.getId() != null
                                && castOther.getId() != null
                                && this.getId().equals(castOther.getId())))
                && (this.getVersion() == castOther.getVersion());
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
        result = 37 * result + (int) this.getVersion();

        return result;
    }
}
